CreditCardED/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.shortcuts import redirect

admin.site.site_header = 'CreditCardED Administration'
admin.site.site_title = 'Admin Panel'
admin.site.index_title = 'Admin Panel'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('client/', include('client.urls')),
    path('server/', include('server.urls')),
    path('server/', lambda request: redirect('encrypted-data/')),
    path('client/', lambda request: redirect('payment/')),
    path('', lambda request: redirect('client/payment/')),
]

client/urls.py
from django.urls import path
from .views import payment_form

app_name = 'client'

urlpatterns = [
    path('payment/', payment_form, name='payment_form'),
]

server/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from . import views
from .views import encrypted_data_list, decrypt_data_view

app_name = 'server'

urlpatterns = [
    path('encrypted-data/', views.encrypted_data_list, name='encrypted_data_list'),
    path('decrypt/<str:encrypted_data_id>/', views.decrypt_data_view, name='decrypt_data_view'),
]

client/models.py
from django.db import models

class EncryptedData(models.Model):
    encrypted_data_base64 = models.TextField()
    identifier = models.CharField(max_length=36)

client/views.py
import os
import uuid
from django.shortcuts import render, redirect
from client.models import EncryptedData
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization, hashes
import base64

def generate_unique_identifier():
    return str(uuid.uuid4())

def encrypt_data(data):
    try:
        identifier = generate_unique_identifier()

        private_key = rsa.generate_private_key(
            public_exponent=65537,
            key_size=2048,
            backend=default_backend()
        )
        public_key = private_key.public_key()

        ciphertext = public_key.encrypt(
            data.encode(),
            padding.OAEP(
                mgf=padding.MGF1(algorithm=hashes.SHA256()),
                algorithm=hashes.SHA256(),
                label=None
            )
        )

        key_folder = os.path.join("server", "private_keys", identifier)
        os.makedirs(key_folder, exist_ok=True)

        key_file_path = os.path.join(key_folder, f"{identifier}_private_key.pem")

        with open(key_file_path, 'wb') as key_file:
            key_file.write(private_key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.TraditionalOpenSSL,
                encryption_algorithm=serialization.NoEncryption()
            ))

        return ciphertext, identifier

    except Exception as e:
        raise ValueError("Error encrypting data:", str(e))

def payment_form(request):
    if request.method == 'POST':
        card_number = request.POST.get('card_number')
        card_holder = request.POST.get('card_holder')
        valid_thru = request.POST.get('valid_thru')
        cvv = request.POST.get('cvv')

        data_to_encrypt = f"{card_number} - {card_holder} - {valid_thru} - {cvv}"

        try:
            encrypted_data, identifier = encrypt_data(data_to_encrypt)
            encrypted_data_base64 = base64.b64encode(encrypted_data).decode('utf-8')

            EncryptedData.objects.create(encrypted_data_base64=encrypted_data_base64, identifier=identifier)

            return render(request, 'client/index.html', {'message': 'Data successfully uploaded!'})

        except Exception as e:
            return render(request, 'client/index.html', {'error': e})

    return render(request, 'client/index.html')

server/views.py
import os
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from client.models import EncryptedData
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.asymmetric import rsa, padding, utils
from cryptography.hazmat.backends import default_backend
import base64

def decrypt_data(encrypted_data_base64, private_key_pem):
    encrypted_data = base64.b64decode(encrypted_data_base64)

    private_key = serialization.load_pem_private_key(
        private_key_pem,
        password=None,
        backend=default_backend()
    )
    decrypted_data = private_key.decrypt(
        encrypted_data,
        padding.OAEP(
            mgf=padding.MGF1(algorithm=hashes.SHA256()),
            algorithm=hashes.SHA256(),
            label=None
        )
    )
    return decrypted_data.decode()

def encrypted_data_list(request):
    encrypted_data_list = EncryptedData.objects.all()
    return render(request, 'server/encrypted_data_list.html', {'encrypted_data_list': encrypted_data_list})

def decrypt_data_view(request, encrypted_data_id):
    try:
        encrypted_data = EncryptedData.objects.get(identifier=encrypted_data_id)
    except ObjectDoesNotExist:
        return redirect('server:encrypted_data_list') 

    if request.method == 'POST':
        selected_key = request.FILES.get('selected_key')
        if selected_key:
            try:
                private_key_pem = selected_key.read()
                decrypted_data = decrypt_data(encrypted_data.encrypted_data_base64, private_key_pem)
                decrypted_data_list = decrypted_data.split(" - ")
                return render(request, 'server/decrypt_data.html', {'encrypted_data': encrypted_data, 'decrypted_data_list': decrypted_data_list})
            except Exception as e:
                error_message = f"Error decrypting data: {e}"
                return render(request, 'server/decrypt_data.html', {'encrypted_data': encrypted_data, 'error_message': error_message})

    return render(request, 'server/decrypt_data.html', {'encrypted_data': encrypted_data})

client/templates/client/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Form</title>
    <link rel="stylesheet" href="{% static 'client/style.css' %}">
</head>
<body>
    {% if error %}
    <div class="alert alert-danger" role="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        {{ error }}
    </div>
    {% elif message %}
    <div class="alert alert-success" role="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        {{ message }}
    </div>
    {% endif %}
    <div class="payment">
        <div class="bg"></div>
        <div class="card">
            <img src="{% static 'client/chip.png' %}" class="chip">
            <div class="logo"></div>
            <h2 class="bankName" contenteditable="true">Payment Gateway</h2>
            <form method="post" action="{% url 'client:payment_form' %}">
                {% csrf_token %}
                <div class="inputBox">
                    <span>Card No.</span>
                    <input type="text" name="card_number" placeholder="0213 1664 4645 7887" maxlength="19" required>
                </div>
                <div class="inputBox">
                    <span>Card Holder</span>
                    <input type="text" name="card_holder" placeholder="Your Name" required>
                </div>
                <div class="group">
                    <div class="inputBox">
                        <span>Valid Thru</span>
                        <input type="text" name="valid_thru" placeholder="MM/YY" maxlength="5" required>
                    </div>
                    <div class="inputBox">
                        <span>CVV</span>
                        <input type="password" name="cvv" placeholder="***" maxlength="4" required>
                    </div>
                </div>
                </div>
                <button type="submit" class="btn">Confirm And Pay</button>
            </form>
    </div>
</body>
</html>

server/templates/server/decrypt_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Decrypt Data</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body style="background-image: linear-gradient(135deg, #74EBD5 8%, #9FACE6 81%); min-height: 90vh;">
    <div class="container mt-5">
        {% if error_message %}
            <div class="alert alert-danger fade show" role="alert">
                <span class="btn-close px-2" style="cursor: pointer;" onclick="this.parentElement.style.display='none';">&times;</span>
                {{ error_message }}
            </div>
        {% endif %}

        <h1>Identifier: {{ encrypted_data.identifier }}</h1>
        <div class="mt-4">
            <h2>Encrypted Data:</h2>
            <p style="word-wrap: break-word; max-width: 100%;">{{ encrypted_data.encrypted_data_base64 }}</p>
        </div>

        <div class="mt-4">
            <h2>Select Private Key:</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <input type="file" name="selected_key">
                </div>
                <button type="submit" class="btn btn-success">Decrypt</button>
            </form>
        </div>

        {% if decrypted_data_list %}
            <div class="mt-4">
                <h2>Decrypted Data:</h2>
                <table class="table table-dark text-center">
                    <thead>
                        <tr>
                            <th>Card Number</th>
                            <th>Card Holder Name</th>
                            <th>Expiration Date</th>
                            <th>CVV Code</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="table-success">
                            {% for item in decrypted_data_list %}
                                <td>{{ item }}</td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
        {% endif %}
    </div>
    <div class="position-fixed top-0 end-0 p-3">
        <a href="/server" class="btn btn-primary">Home</a>
    </div>
</body>
</html>

server/templates/server/encrypted_data_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Encrypted Data List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body style="background-image: linear-gradient(135deg, #74EBD5 8%, #9FACE6 81%); min-height: 90vh;">
    <div class="container align-items-center my-5">
        <table class="table table-bordered table-striped table-hover text-center">
            <thead>
                <tr class="table-dark">
                    <th scope="col">Sr. No.</th>
                    <th scope="col">Identifier</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for data in encrypted_data_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td> 
                        <td>{{ data.identifier }}</td>
                        <td>
                            <form method="post" action="{% url 'server:decrypt_data_view' data.identifier %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-sm btn-outline-primary">Decrypt</button>
                            </form>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3" class="text-muted">No data available.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>